import { chronologicalSplit, evaluateModel, exportModelBundle, trainLogisticRegression, trainTreeEnsemble, trainWeightedModel, walkForwardSplits, type TimeSeriesSample } from "@/lib/platform/ensemble";
import { apiError, protectMutation, readJson } from "@/lib/platform/http";
import { stableHash } from "@/lib/platform/math";
import { saveModel } from "@/lib/platform/store";

export async function POST(request: Request) {
  const auth = protectMutation(request); if (auth.response) return auth.response;
  try {
    const body = await readJson<{ name: string; type: "fixed-weight" | "optimized-weight" | "logistic-regression" | "random-forest" | "gradient-boosted-tree"; featureNames: string[]; samples: TimeSeriesSample[]; timeframe: string; strategies?: Record<string, unknown>[]; purge?: number; embargo?: number; seed?: number; automaticPromotionEligible?: boolean }>(request, 5_000_000); if (!body.name?.trim()) throw new Error("Model name is required"); const split = chronologicalSplit(body.samples, { trainRatio: 0.6, validationRatio: 0.2, purge: body.purge ?? 1, embargo: body.embargo ?? 1 }); const seed = body.seed ?? 42; const model = body.type === "fixed-weight" || body.type === "optimized-weight" ? trainWeightedModel(body.type, split.train, body.featureNames, undefined, seed) : body.type === "logistic-regression" ? trainLogisticRegression(split.train, body.featureNames, { seed }) : trainTreeEnsemble(body.type, split.train, body.featureNames, { seed }); const validation = evaluateModel(model, split.validation); const test = evaluateModel(model, split.test); const folds = walkForwardSplits([...split.train, ...split.validation], 3, body.purge ?? 1, body.embargo ?? 1).map((fold) => evaluateModel(model, fold.validation)); const baseline = { directionalAccuracy: 0.5, meanSquaredError: body.samples.reduce((sum, sample) => sum + sample.label ** 2, 0) / body.samples.length }; const datasetVersion = `training_${stableHash(JSON.stringify(body.samples))}`; const bundle = exportModelBundle(model, { timeframe: body.timeframe, warmupBars: 52, strategies: body.strategies ?? [], riskPolicy: "max-exposure-drawdown@1.0.0", trainingMetadata: { datasetVersion, split: split.boundaries, validation, test, folds, baseline, seed, shuffled: false }, sampleInputs: body.samples.slice(0, 3).map((sample) => sample.features) }); await saveModel(auth.email!, { id: model.id, name: body.name.trim(), version: `${model.version}+${datasetVersion.slice(-8)}`, modelType: model.type, bundle, metrics: { validation, test, folds, baseline }, datasetVersion, featureVersion: bundle.manifest.inputSchema, automaticPromotionEligible: body.automaticPromotionEligible }); return Response.json({ model: model.serialize(), bundle, datasetVersion, validation, test, folds, baseline, promotionEligible: test.directionalAccuracy > baseline.directionalAccuracy && validation.directionalAccuracy > baseline.directionalAccuracy }, { status: 201, headers: { "Cache-Control": "no-store" } });
  } catch (error) { return apiError(error, "Training failed"); }
}
