import assert from "node:assert/strict";
import test from "node:test";
import type { Candle, ExperimentConfiguration } from "../lib/platform/contracts";
import { INDICATOR_PLUGINS } from "../lib/platform/indicators";
import { STRATEGY_PLUGINS } from "../lib/platform/strategies";
import { createDatasetManifest, missingCoverage, parseCsvCandles, validateCandles } from "../lib/platform/data";
import { runBacktest } from "../lib/platform/backtest";
import { chronologicalSplit, evaluateModel, exportModelBundle, importModelBundle, trainLogisticRegression, walkForwardSplits } from "../lib/platform/ensemble";
import { initialPaperState, processCompletedCandle, transitionPaperState } from "../lib/platform/paper";
import { pluginCatalog } from "../lib/platform/registry";
import { simulateOrder } from "../lib/platform/execution";

const HOUR = 3_600_000;
function candles(length = 220): Candle[] { return Array.from({ length }, (_, index) => { const prior = 100 + index * 0.08 + Math.sin((index - 1) / 7) * 3; const close = 100 + index * 0.08 + Math.sin(index / 7) * 3; return { timestamp: index * HOUR, open: prior, high: Math.max(prior, close) + 0.8, low: Math.min(prior, close) - 0.8, close, volume: 1000 + index * 2, symbol: "BTC/USDT", timeframe: "1h", complete: true }; }); }

test("registers every required plugin with a supported interface", () => { const catalog = pluginCatalog(); assert.equal(INDICATOR_PLUGINS.length, 18); assert.equal(STRATEGY_PLUGINS.length, 11); assert.ok(catalog.every((plugin) => plugin.interfaceVersion === "1.0")); for (const kind of ["venue", "data-provider", "indicator", "strategy", "risk", "execution", "fee", "slippage", "ai-model", "metric"]) assert.ok(catalog.some((plugin) => plugin.kind === kind), `missing ${kind}`); });

test("indicator outputs are deterministic, aligned, and prefix-stable", () => { const fixture = candles(); for (const indicator of INDICATOR_PLUGINS) { const first = indicator.calculate(fixture); const second = indicator.calculate(fixture); assert.deepEqual(first, second, indicator.id); for (const column of indicator.outputColumns) assert.equal(first[column].length, fixture.length, `${indicator.id}.${column}`); const prefix = indicator.calculate(fixture.slice(0, 150)); for (const column of indicator.outputColumns) assert.deepEqual(prefix[column], first[column].slice(0, 150), `${indicator.id} leaked future data`); } });

test("strategy signals obey the normalized contract and do not look ahead", () => { const fixture = candles(); for (const strategy of STRATEGY_PLUGINS) { const signals = strategy.generate(fixture); assert.equal(signals.length, fixture.length); assert.ok(signals.every((signal) => [-1, 0, 1].includes(signal.direction) && signal.confidence >= 0 && signal.confidence <= 1 && signal.desiredExposure >= -1 && signal.desiredExposure <= 1)); const prefix = strategy.generate(fixture.slice(0, 150)); assert.deepEqual(prefix, signals.slice(0, 150), `${strategy.id} leaked future data`); } });

test("CSV normalization, quality gates, coverage, and manifests are reproducible", () => { const csv = "timestamp,open,high,low,close,volume\n1970-01-01T00:00:00Z,10,12,9,11,100\n1970-01-01T01:00:00Z,11,13,10,12,120"; const parsed = parseCsvCandles(csv, { symbol: "GOLD/USD", timeframe: "1h" }); assert.equal(validateCandles(parsed, "1h").valid, true); assert.deepEqual(missingCoverage(parsed, 0, HOUR * 2, "1h"), [{ start: HOUR * 2, end: HOUR * 2 }]); const request = { provider: "generic-csv", symbol: "GOLD/USD", timeframe: "1h" as const, start: 0, end: HOUR, marketType: "commodity" as const }; assert.equal(createDatasetManifest("generic-csv", request, "GOLD/USD", parsed).id, createDatasetManifest("generic-csv", request, "GOLD/USD", parsed).id); });

test("backtests are deterministic and execute signals no earlier than the next bar", () => { const fixture = candles(); const configuration: ExperimentConfiguration = { provider: "fixture", marketType: "spot", symbols: ["BTCUSDT"], timeframe: "1h", start: 0, end: fixture.at(-1)!.timestamp, strategies: [{ id: "moving-average-crossover" }, { id: "rsi-mean-reversion" }], initialCash: 100_000, leverage: 1, feeBps: 10, spreadBps: 2, slippageBps: 5, maxExposure: 1, maxDrawdown: 0.25, executionTiming: "next-open", seed: 42 }; const first = runBacktest(configuration, { BTCUSDT: fixture }, ["fixture-v1"]); const second = runBacktest(configuration, { BTCUSDT: fixture }, ["fixture-v1"]); assert.deepEqual(first.trades, second.trades); assert.deepEqual(first.equity, second.equity); assert.ok(first.trades.every((trade) => first.signals.some((signal) => signal.timestamp < trade.timestamp))); assert.ok(first.metrics.fees >= 0 && first.metrics.slippage >= 0); });

test("execution supports market, limit, stop, stop-limit, rejection, and partial fills",()=>{const candle={...candles(1)[0],open:100,high:110,low:90,close:105,volume:10};const rules={tickSize:.01,lotSize:.001,minimumQuantity:.01,minimumNotional:5,maximumVolumeParticipation:.1,allowShort:false};const costs={feeBps:10,spreadBps:2,slippageBps:5};assert.equal(simulateOrder({id:"m",symbol:"BTC",side:"buy",type:"market",quantity:2,createdAt:0},candle,rules,costs).status,"partially-filled");assert.equal(simulateOrder({id:"l",symbol:"BTC",side:"buy",type:"limit",quantity:.5,limitPrice:95,createdAt:0},candle,rules,costs).status,"filled");assert.equal(simulateOrder({id:"s",symbol:"BTC",side:"buy",type:"stop",quantity:.5,stopPrice:108,createdAt:0},candle,rules,costs).status,"filled");assert.equal(simulateOrder({id:"sl",symbol:"BTC",side:"buy",type:"stop-limit",quantity:.5,stopPrice:108,limitPrice:106,createdAt:0},candle,rules,costs).status,"filled");assert.match(simulateOrder({id:"short",symbol:"BTC",side:"sell",type:"market",quantity:.5,createdAt:0},candle,rules,costs,0).reason??"",/short/i);});

test("futures funding is charged deterministically",()=>{const fixture=candles().map((candle,index)=>({...candle,fundingRate:index%8===0?.0001:0}));const configuration:ExperimentConfiguration={provider:"fixture",marketType:"futures",symbols:["BTCUSDT"],timeframe:"1h",start:0,end:fixture.at(-1)!.timestamp,strategies:[{id:"buy-and-hold"}],initialCash:100_000,leverage:2,feeBps:5,spreadBps:1,slippageBps:1,maxExposure:1,maxDrawdown:.4,executionTiming:"next-open",seed:42};const result=runBacktest(configuration,{BTCUSDT:fixture});assert.ok((result.fundingPayments?.length??0)>0);assert.notEqual(result.metrics.funding,0);});

test("chronological validation purges boundaries and model bundles reproduce predictions", () => { const samples = Array.from({ length: 120 }, (_, index) => ({ timestamp: index, features: [Math.sin(index / 5), Math.cos(index / 9)], label: Math.sin((index + 2) / 5) * 0.01 })); const split = chronologicalSplit(samples, { trainRatio: 0.6, validationRatio: 0.2, purge: 2, embargo: 2 }); assert.ok(split.train.at(-1)!.timestamp < split.validation[0].timestamp); assert.ok(split.validation.at(-1)!.timestamp < split.test[0].timestamp); assert.equal(walkForwardSplits(samples, 3, 2, 2).length, 3); const model = trainLogisticRegression(split.train, ["signal-a", "signal-b"]); assert.equal(evaluateModel(model, split.test).observations, split.test.length); const bundle = exportModelBundle(model, { timeframe: "1h", warmupBars: 52, strategies: [], riskPolicy: "risk@1", trainingMetadata: { split: split.boundaries }, sampleInputs: samples.slice(0, 4).map((sample) => sample.features) }); const imported = importModelBundle(JSON.parse(JSON.stringify(bundle))); assert.deepEqual(imported.predict([[0.2, -0.3]], [999]), model.predict([[0.2, -0.3]], [999])); const corrupted = JSON.parse(JSON.stringify(bundle)); corrupted.model.parameters.bias = 100; assert.throws(() => importModelBundle(corrupted), /checksum/i); });

test("paper trading rejects incomplete data, deduplicates events, and recovers serialized state", () => { const configuration = { sessionId: "paper-1", modelId: "model-1", modelVersion: "1", symbol: "BTC/USDT", timeframe: "1h", initialCash: 10_000, feeBps: 10, spreadBps: 2, slippageBps: 3, maxExposure: 1, maxDrawdown: 0.2 }; let state = transitionPaperState(initialPaperState(configuration), "start"); const candle = candles(1)[0]; const prediction = { timestamp: candle.timestamp, expectedReturn: 0.01, probabilityProfitable: 0.8, direction: 1 as const, targetExposure: 0.6 }; assert.throws(() => processCompletedCandle(configuration, state, { ...candle, complete: false }, prediction), /Incomplete/); state = processCompletedCandle(configuration, state, candle, prediction); const recovered = JSON.parse(JSON.stringify(state)); assert.deepEqual(processCompletedCandle(configuration, recovered, candle, prediction), recovered); assert.equal(state.trades.length, 1); assert.equal(transitionPaperState(state, "emergency-stop").status, "stopped"); });
