import type { BacktestResult, Candle, ExperimentConfiguration, PerformanceMetrics, StrategySignal, Trade } from "./contracts";
import { clamp, mean, stableHash, standardDeviation } from "./math";
import { requireStrategy } from "./strategies";
import { TIMEFRAME_MILLISECONDS } from "./data";

const money = (value: number) => Math.round(value * 1e8) / 1e8;

interface Position { quantity: number; averagePrice: number; }

function returnsFromEquity(equity: BacktestResult["equity"]) {
  return equity.slice(1).map((point, index) => equity[index].equity ? point.equity / equity[index].equity - 1 : 0);
}

function periodReturns(equity: BacktestResult["equity"], period: "month" | "year") {
  const buckets = new Map<string, { first: number; last: number }>();
  for (const point of equity) { const date = new Date(point.timestamp); const key = period === "year" ? String(date.getUTCFullYear()) : `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; const current = buckets.get(key); if (current) current.last = point.equity; else buckets.set(key, { first: point.equity, last: point.equity }); }
  return Object.fromEntries([...buckets].map(([key, value]) => [key, value.first ? value.last / value.first - 1 : 0]));
}

export function calculateMetrics(result: Pick<BacktestResult, "equity" | "trades">, initialCash: number, firstClose: number, lastClose: number, timeframeMilliseconds: number, funding = 0): PerformanceMetrics {
  const equity = result.equity; const trades = result.trades; const finalEquity = equity.at(-1)?.equity ?? initialCash; const returns = returnsFromEquity(equity); const periodsPerYear = 365.25 * 86_400_000 / timeframeMilliseconds; const average = mean(returns); const deviation = standardDeviation(returns); const downside = Math.sqrt(mean(returns.filter((value) => value < 0).map((value) => value ** 2))); let peak = initialCash; let maximumDrawdown = 0;
  for (const point of equity) { peak = Math.max(peak, point.equity); maximumDrawdown = Math.max(maximumDrawdown, peak ? (peak - point.equity) / peak : 0); }
  const years = Math.max(timeframeMilliseconds / (365.25 * 86_400_000), (equity.length * timeframeMilliseconds) / (365.25 * 86_400_000)); const netReturn = finalEquity / initialCash - 1; const annualizedReturn = years > 0 ? Math.pow(Math.max(finalEquity / initialCash, 0), 1 / years) - 1 : 0; const closed = trades.filter((trade) => trade.realizedPnl !== 0); const wins = closed.filter((trade) => trade.realizedPnl > 0); const losses = closed.filter((trade) => trade.realizedPnl < 0); const grossWins = wins.reduce((sum, trade) => sum + trade.realizedPnl, 0); const grossLosses = Math.abs(losses.reduce((sum, trade) => sum + trade.realizedPnl, 0)); const fees = trades.reduce((sum, trade) => sum + trade.fee, 0); const slippage = trades.reduce((sum, trade) => sum + trade.slippage, 0); const sorted = [...returns].sort((a, b) => a - b); const varIndex = Math.max(0, Math.floor(sorted.length * 0.05) - 1); const exposureBars = equity.filter((point) => Math.abs(point.exposure) > 1e-12).length;
  return { grossReturn: (finalEquity + fees + slippage + funding) / initialCash - 1, netReturn, annualizedReturn, buyAndHoldReturn: firstClose ? lastClose / firstClose - 1 : 0, maximumDrawdown, sharpe: deviation ? average / deviation * Math.sqrt(periodsPerYear) : 0, sortino: downside ? average / downside * Math.sqrt(periodsPerYear) : 0, calmar: maximumDrawdown ? annualizedReturn / maximumDrawdown : 0, profitFactor: grossLosses ? grossWins / grossLosses : grossWins ? Number.POSITIVE_INFINITY : 0, winRate: closed.length ? wins.length / closed.length : 0, expectancy: closed.length ? (grossWins - grossLosses) / closed.length : 0, averageWin: wins.length ? grossWins / wins.length : 0, averageLoss: losses.length ? -grossLosses / losses.length : 0, trades: trades.length, exposureTime: equity.length ? exposureBars / equity.length : 0, turnover: trades.reduce((sum, trade) => sum + Math.abs(trade.quantity * trade.fillPrice), 0) / initialCash, fees, funding, slippage, valueAtRisk95: sorted.length ? -sorted[varIndex] : 0 };
}

export function validateExperiment(configuration: ExperimentConfiguration) {
  if (!configuration.symbols.length) throw new Error("At least one symbol is required"); if (!configuration.strategies.length) throw new Error("At least one strategy is required"); if (!(configuration.start < configuration.end)) throw new Error("Experiment start must precede end"); if (!(configuration.initialCash > 0)) throw new Error("Initial cash must be positive"); if (configuration.leverage < 1 || configuration.leverage > 20) throw new Error("Leverage must be between 1 and 20"); if (configuration.marketType === "spot" && configuration.leverage !== 1) throw new Error("Spot experiments cannot use leverage"); if (configuration.maxExposure <= 0 || configuration.maxExposure > configuration.leverage) throw new Error("Maximum exposure exceeds leverage"); if (configuration.maxDrawdown <= 0 || configuration.maxDrawdown > 1) throw new Error("Maximum drawdown must be between zero and one"); configuration.strategies.forEach((entry) => requireStrategy(entry.id));
}

export function runBacktest(configuration: ExperimentConfiguration, datasets: Record<string, readonly Candle[]>, datasetIds: string[] = []): BacktestResult {
  validateExperiment(configuration); const interval = TIMEFRAME_MILLISECONDS[configuration.timeframe]; const symbols = configuration.symbols.map((symbol) => symbol.toUpperCase()); for (const symbol of symbols) if (!datasets[symbol]?.length) throw new Error(`No candles supplied for ${symbol}`);
  const signalsBySymbol = new Map<string, Map<number, StrategySignal[]>>(); const allSignals: StrategySignal[] = [];
  for (const symbol of symbols) { const candles = datasets[symbol].filter((candle) => candle.complete && candle.timestamp >= configuration.start && candle.timestamp <= configuration.end); const byTimestamp = new Map<number, StrategySignal[]>(); for (const selected of configuration.strategies) { const generated = requireStrategy(selected.id).generate(candles, selected.parameters); generated.forEach((signal) => { const list = byTimestamp.get(signal.timestamp) ?? []; list.push(signal); byTimestamp.set(signal.timestamp, list); allSignals.push({ ...signal, metadata: { ...signal.metadata, symbol } }); }); } signalsBySymbol.set(symbol, byTimestamp); }
  const timeline = [...new Set(symbols.flatMap((symbol) => datasets[symbol].map((candle) => candle.timestamp)))].sort((a, b) => a - b).filter((timestamp) => timestamp >= configuration.start && timestamp <= configuration.end); const candleMaps = new Map(symbols.map((symbol) => [symbol, new Map(datasets[symbol].map((candle) => [candle.timestamp, candle]))])); const positions = new Map<string, Position>(symbols.map((symbol) => [symbol, { quantity: 0, averagePrice: 0 }])); let cash = configuration.initialCash; let peakEquity = cash; let stopped = false; const trades: Trade[] = []; const equity: BacktestResult["equity"] = []; const fundingPayments: NonNullable<BacktestResult["fundingPayments"]> = [];
  for (let timelineIndex = 0; timelineIndex < timeline.length; timelineIndex += 1) { const timestamp = timeline[timelineIndex]; const markEquity = () => money(cash + symbols.reduce((sum, symbol) => sum + (positions.get(symbol)?.quantity ?? 0) * (candleMaps.get(symbol)?.get(timestamp)?.close ?? positions.get(symbol)?.averagePrice ?? 0), 0)); let currentEquity = markEquity(); peakEquity = Math.max(peakEquity, currentEquity); if (peakEquity && (peakEquity - currentEquity) / peakEquity >= configuration.maxDrawdown) stopped = true;
    if (timelineIndex > 0) { const signalTimestamp = timeline[timelineIndex - 1]; for (const symbol of symbols) { const candle = candleMaps.get(symbol)?.get(timestamp); if (!candle?.complete) continue; const position = positions.get(symbol)!; const signals = signalsBySymbol.get(symbol)?.get(signalTimestamp) ?? []; const desired = stopped ? 0 : signals.length ? mean(signals.map((signal) => signal.desiredExposure)) : position.quantity * candle.open / Math.max(currentEquity, 1); const allowedDesired = configuration.marketType === "spot" ? clamp(desired, 0, configuration.maxExposure) : clamp(desired, -configuration.maxExposure, configuration.maxExposure); const executionPrice = configuration.executionTiming === "next-close" ? candle.close : candle.open; const targetNotional = currentEquity * allowedDesired; const targetQuantity = targetNotional / executionPrice; let requestedQuantity = targetQuantity - position.quantity; const liquidityQuantity = candle.volume > 0 ? candle.volume * 0.1 : Math.abs(requestedQuantity); requestedQuantity = clamp(requestedQuantity, -liquidityQuantity, liquidityQuantity); if (Math.abs(requestedQuantity * executionPrice) < 1e-8) continue;
        const side = requestedQuantity > 0 ? "buy" : "sell"; const spreadRate = configuration.spreadBps / 20_000; const slippageRate = configuration.slippageBps / 10_000 * Math.min(1, Math.abs(requestedQuantity) / Math.max(liquidityQuantity, 1e-12)); const fillPrice = executionPrice * (1 + (side === "buy" ? 1 : -1) * (spreadRate + slippageRate)); const notional = Math.abs(requestedQuantity * fillPrice); const fee = money(notional * configuration.feeBps / 10_000); const slippage = money(Math.abs(requestedQuantity) * Math.abs(fillPrice - executionPrice)); let realizedPnl = 0;
        if (position.quantity !== 0 && Math.sign(requestedQuantity) !== Math.sign(position.quantity)) { const closingQuantity = Math.min(Math.abs(requestedQuantity), Math.abs(position.quantity)); realizedPnl = money(closingQuantity * (fillPrice - position.averagePrice) * Math.sign(position.quantity)); }
        cash = money(cash - requestedQuantity * fillPrice - fee); const newQuantity = money(position.quantity + requestedQuantity); if (newQuantity === 0 || Math.sign(newQuantity) !== Math.sign(position.quantity)) position.averagePrice = newQuantity === 0 ? 0 : fillPrice; else if (Math.sign(requestedQuantity) === Math.sign(position.quantity) || position.quantity === 0) position.averagePrice = (Math.abs(position.quantity) * position.averagePrice + Math.abs(requestedQuantity) * fillPrice) / Math.abs(newQuantity); position.quantity = newQuantity;
        trades.push({ id: `trade_${stableHash(`${symbol}:${timestamp}:${trades.length}`)}`, strategyId: signals.map((signal) => signal.strategyId).join("+") || "risk-engine", symbol, side, quantity: Math.abs(requestedQuantity), requestedPrice: executionPrice, fillPrice, timestamp, fee, slippage, realizedPnl });
      } }
    if(configuration.marketType==="futures"){for(const symbol of symbols){const candle=candleMaps.get(symbol)?.get(timestamp);const position=positions.get(symbol)!;if(candle?.fundingRate&&position.quantity){const amount=money(position.quantity*candle.close*candle.fundingRate);cash=money(cash-amount);fundingPayments.push({timestamp,symbol,amount});}}}
    currentEquity = markEquity(); const grossExposure = symbols.reduce((sum, symbol) => sum + Math.abs((positions.get(symbol)?.quantity ?? 0) * (candleMaps.get(symbol)?.get(timestamp)?.close ?? 0)), 0); equity.push({ timestamp, equity: currentEquity, cash, exposure: currentEquity ? grossExposure / currentEquity : 0 });
  }
  const firstSymbolCandles = datasets[symbols[0]].filter((c) => c.timestamp >= configuration.start && c.timestamp <= configuration.end); const id = `bt_${stableHash(JSON.stringify({ configuration, datasetIds }))}`; const result: BacktestResult = { id, configuration, datasetIds, codeVersion: process.env.SOURCE_COMMIT || "development", createdAt: new Date().toISOString(), signals: allSignals, trades, equity, metrics: {} as PerformanceMetrics, monthlyReturns: {}, annualReturns: {}, fundingPayments }; result.metrics = calculateMetrics(result, configuration.initialCash, firstSymbolCandles[0]?.close ?? 0, firstSymbolCandles.at(-1)?.close ?? 0, interval, fundingPayments.reduce((sum,item)=>sum+item.amount,0)); result.monthlyReturns = periodReturns(equity, "month"); result.annualReturns = periodReturns(equity, "year"); return result;
}
