import type { ModelPrediction, SerializableModel } from "./contracts";
import { clamp, mean, seededRandom, sigmoid, stableHash } from "./math";

export interface TimeSeriesSample { timestamp: number; features: number[]; label: number; }
export interface SplitConfiguration { trainRatio: number; validationRatio: number; purge: number; embargo: number; }
export interface DatasetSplit { train: TimeSeriesSample[]; validation: TimeSeriesSample[]; test: TimeSeriesSample[]; boundaries: { trainEnd: number; validationStart: number; validationEnd: number; testStart: number } }

export function chronologicalSplit(samples: readonly TimeSeriesSample[], configuration: SplitConfiguration): DatasetSplit {
  if (samples.length < 20) throw new Error("At least 20 chronological samples are required"); if (!(configuration.trainRatio > 0 && configuration.validationRatio > 0 && configuration.trainRatio + configuration.validationRatio < 1)) throw new Error("Invalid chronological split ratios");
  const ordered = [...samples].sort((a, b) => a.timestamp - b.timestamp); for (let i = 1; i < ordered.length; i += 1) if (ordered[i].timestamp <= ordered[i - 1].timestamp) throw new Error("Training timestamps must be unique and strictly increasing");
  const rawTrainEnd = Math.floor(ordered.length * configuration.trainRatio); const rawValidationEnd = Math.floor(ordered.length * (configuration.trainRatio + configuration.validationRatio)); const purge = Math.max(0, Math.floor(configuration.purge)); const embargo = Math.max(0, Math.floor(configuration.embargo)); const validationStart = rawTrainEnd + embargo; const testStart = rawValidationEnd + embargo;
  const train = ordered.slice(0, Math.max(0, rawTrainEnd - purge)); const validation = ordered.slice(validationStart, Math.max(validationStart, rawValidationEnd - purge)); const test = ordered.slice(testStart); if (!train.length || !validation.length || !test.length) throw new Error("Purging and embargo leave an empty dataset split"); return { train, validation, test, boundaries: { trainEnd: train.at(-1)!.timestamp, validationStart: validation[0].timestamp, validationEnd: validation.at(-1)!.timestamp, testStart: test[0].timestamp } };
}

export function walkForwardSplits(samples: readonly TimeSeriesSample[], folds = 4, purge = 1, embargo = 1) {
  if (folds < 2) throw new Error("Walk-forward validation requires at least two folds"); const ordered = [...samples].sort((a, b) => a.timestamp - b.timestamp); const window = Math.floor(ordered.length / (folds + 1)); if (window <= purge + embargo) throw new Error("Not enough observations for walk-forward configuration"); return Array.from({ length: folds }, (_, index) => { const trainEnd = window * (index + 1); const validationStart = trainEnd + embargo; return { train: ordered.slice(0, trainEnd - purge), validation: ordered.slice(validationStart, Math.min(ordered.length, validationStart + window)) }; }).filter((fold) => fold.train.length && fold.validation.length);
}

class PortableModel implements SerializableModel {
  constructor(public id: string, public type: SerializableModel["type"], public version: string, public featureNames: string[], public parameters: Record<string, unknown>) {}
  predict(features: number[][], timestamps: number[] = []) {
    const weights = (this.parameters.weights as number[] | undefined) ?? []; const bias = Number(this.parameters.bias ?? 0); const stumps = (this.parameters.stumps as Array<{ feature: number; threshold: number; left: number; right: number }> | undefined) ?? [];
    return features.map((row, index): ModelPrediction => { let score = weights.length ? bias + row.reduce((sum, value, featureIndex) => sum + value * (weights[featureIndex] ?? 0), 0) : stumps.reduce((sum, stump) => sum + (row[stump.feature] <= stump.threshold ? stump.left : stump.right), bias); if (this.type === "fixed-weight" || this.type === "optimized-weight") score = clamp(score, -1, 1); const probability = this.type.includes("weight") ? (score + 1) / 2 : sigmoid(score); const expectedReturn = (probability - 0.5) * 2 * Number(this.parameters.returnScale ?? 0.01); const threshold = Number(this.parameters.decisionThreshold ?? 0.55); const direction = probability >= threshold ? 1 as const : probability <= 1 - threshold ? -1 as const : 0 as const; return { timestamp: timestamps[index] ?? index, expectedReturn, probabilityProfitable: probability, direction, targetExposure: direction * clamp(Math.abs(probability - 0.5) * 2, 0, 1) }; });
  }
  serialize() { return { id: this.id, type: this.type, version: this.version, featureNames: this.featureNames, parameters: this.parameters }; }
}

function normalizeWeights(weights: number[]) { const total = weights.reduce((sum, value) => sum + Math.abs(value), 0); return total ? weights.map((value) => value / total) : weights.map(() => 1 / weights.length); }

export function trainWeightedModel(type: "fixed-weight" | "optimized-weight", samples: readonly TimeSeriesSample[], featureNames: string[], suppliedWeights?: number[], seed = 42) {
  if (!samples.length || !featureNames.length) throw new Error("Weighted ensemble requires training samples and features"); let weights = suppliedWeights?.length === featureNames.length ? normalizeWeights(suppliedWeights) : featureNames.map(() => 1 / featureNames.length);
  if (type === "optimized-weight") { const random = seededRandom(seed); let best = weights; let bestLoss = Number.POSITIVE_INFINITY; for (let iteration = 0; iteration < 800; iteration += 1) { const candidate = normalizeWeights(weights.map(() => random() * 2 - 1)); const loss = mean(samples.map((sample) => (sample.label - sample.features.reduce((sum, value, index) => sum + value * candidate[index], 0)) ** 2)); if (loss < bestLoss) { bestLoss = loss; best = candidate; } } weights = best; }
  return new PortableModel(`model_${stableHash(JSON.stringify({ type, weights, seed }))}`, type, "1.0.0", featureNames, { weights, bias: 0, decisionThreshold: 0.55, returnScale: Math.max(0.001, mean(samples.map((sample) => Math.abs(sample.label)))) });
}

export function trainLogisticRegression(samples: readonly TimeSeriesSample[], featureNames: string[], options: { iterations?: number; learningRate?: number; l2?: number; seed?: number } = {}) {
  if (!samples.length || samples.some((sample) => sample.features.length !== featureNames.length)) throw new Error("Logistic training data does not match feature schema"); const iterations = options.iterations ?? 600; const rate = options.learningRate ?? 0.05; const l2 = options.l2 ?? 0.001; let weights = featureNames.map(() => 0); let bias = 0;
  for (let iteration = 0; iteration < iterations; iteration += 1) { const gradient = weights.map(() => 0); let biasGradient = 0; for (const sample of samples) { const expected = sample.label > 0 ? 1 : 0; const predicted = sigmoid(bias + sample.features.reduce((sum, value, index) => sum + value * weights[index], 0)); const error = predicted - expected; sample.features.forEach((value, index) => gradient[index] += error * value); biasGradient += error; } weights = weights.map((weight, index) => weight - rate * (gradient[index] / samples.length + l2 * weight)); bias -= rate * biasGradient / samples.length; }
  return new PortableModel(`model_${stableHash(JSON.stringify({ type: "logistic-regression", weights, bias }))}`, "logistic-regression", "1.0.0", featureNames, { weights, bias, decisionThreshold: 0.55, returnScale: Math.max(0.001, mean(samples.map((sample) => Math.abs(sample.label)))) });
}

function bestStump(samples: readonly TimeSeriesSample[], featureCount: number, residuals: number[], candidates = 12) {
  let best = { feature: 0, threshold: 0, left: 0, right: 0, loss: Number.POSITIVE_INFINITY };
  for (let feature = 0; feature < featureCount; feature += 1) { const values = samples.map((sample) => sample.features[feature]).sort((a, b) => a - b); for (let step = 1; step < candidates; step += 1) { const threshold = values[Math.floor(values.length * step / candidates)] ?? 0; const leftValues = residuals.filter((_, index) => samples[index].features[feature] <= threshold); const rightValues = residuals.filter((_, index) => samples[index].features[feature] > threshold); const left = mean(leftValues); const right = mean(rightValues); const loss = samples.reduce((sum, sample, index) => sum + (residuals[index] - (sample.features[feature] <= threshold ? left : right)) ** 2, 0); if (loss < best.loss) best = { feature, threshold, left, right, loss }; } }
  return best;
}

export function trainTreeEnsemble(type: "random-forest" | "gradient-boosted-tree", samples: readonly TimeSeriesSample[], featureNames: string[], options: { trees?: number; learningRate?: number; seed?: number } = {}) {
  if (!samples.length || !featureNames.length) throw new Error("Tree ensemble requires training samples and features"); const trees = Math.max(1, Math.min(200, options.trees ?? 30)); const learningRate = type === "gradient-boosted-tree" ? clamp(options.learningRate ?? 0.1, 0.001, 1) : 1 / trees; const random = seededRandom(options.seed ?? 42); const labels = samples.map((sample) => sample.label > 0 ? 1 : -1); const predictions = samples.map(() => 0); const stumps = [];
  for (let tree = 0; tree < trees; tree += 1) { const residuals = type === "gradient-boosted-tree" ? labels.map((label, index) => label - predictions[index]) : labels; const subset = type === "random-forest" ? samples.map((_, index) => ({ sample: samples[Math.floor(random() * samples.length)], residual: residuals[index] })) : samples.map((sample, index) => ({ sample, residual: residuals[index] })); const stump = bestStump(subset.map((item) => item.sample), featureNames.length, subset.map((item) => item.residual)); const weighted = { feature: stump.feature, threshold: stump.threshold, left: stump.left * learningRate, right: stump.right * learningRate }; stumps.push(weighted); samples.forEach((sample, index) => predictions[index] += sample.features[weighted.feature] <= weighted.threshold ? weighted.left : weighted.right); }
  return new PortableModel(`model_${stableHash(JSON.stringify({ type, stumps }))}`, type, "1.0.0", featureNames, { stumps, bias: 0, decisionThreshold: 0.55, returnScale: Math.max(0.001, mean(samples.map((sample) => Math.abs(sample.label)))) });
}

export function evaluateModel(model: SerializableModel, samples: readonly TimeSeriesSample[]) {
  const predictions = model.predict(samples.map((sample) => sample.features), samples.map((sample) => sample.timestamp)); const errors = predictions.map((prediction, index) => prediction.expectedReturn - samples[index].label); const correct = predictions.filter((prediction, index) => prediction.direction === 0 || Math.sign(samples[index].label) === prediction.direction).length; const positive = predictions.map((prediction) => prediction.probabilityProfitable); const labels = samples.map((sample) => sample.label > 0 ? 1 : 0); return { observations: samples.length, meanSquaredError: mean(errors.map((error) => error ** 2)), directionalAccuracy: samples.length ? correct / samples.length : 0, brierScore: mean(positive.map((probability, index) => (probability - labels[index]) ** 2)), averagePrediction: mean(predictions.map((prediction) => prediction.expectedReturn)) };
}

export function deserializeModel(payload: Record<string, unknown>) {
  const types = ["fixed-weight", "optimized-weight", "logistic-regression", "random-forest", "gradient-boosted-tree", "neural-network"]; if (typeof payload.id !== "string" || !types.includes(String(payload.type)) || !Array.isArray(payload.featureNames) || !payload.featureNames.every((item) => typeof item === "string") || typeof payload.parameters !== "object" || !payload.parameters) throw new Error("Invalid portable model payload"); return new PortableModel(payload.id, payload.type as SerializableModel["type"], String(payload.version ?? "1.0.0"), payload.featureNames as string[], payload.parameters as Record<string, unknown>);
}

export interface ModelBundle { compatibilityVersion: "1.0"; manifest: { bundleId: string; modelId: string; modelVersion: string; createdAt: string; checksum: string; inputSchema: string; timeframe: string; warmupBars: number }; model: Record<string, unknown>; featureSchema: Array<{ name: string; type: "number"; order: number }>; preprocessing: { missing: "reject"; scaling: "embedded" | "none" }; strategyConfigurations: Record<string, unknown>[]; decisionThresholds: { profitable: number }; riskPolicy: string; trainingMetadata: Record<string, unknown>; modelCard: string; testVectors: Array<{ input: number[]; expected: ModelPrediction }> }

export function exportModelBundle(model: SerializableModel, options: { timeframe: string; warmupBars: number; strategies: Record<string, unknown>[]; riskPolicy: string; trainingMetadata: Record<string, unknown>; sampleInputs: number[][] }): ModelBundle {
  const serialized = model.serialize(); const predictions = model.predict(options.sampleInputs, options.sampleInputs.map((_, index) => index)); const checksum = stableHash(JSON.stringify(serialized)); const bundleId = `bundle_${stableHash(JSON.stringify({ checksum, options }))}`; return { compatibilityVersion: "1.0", manifest: { bundleId, modelId: model.id, modelVersion: model.version, createdAt: new Date().toISOString(), checksum, inputSchema: "tradepilot-features-1.0", timeframe: options.timeframe, warmupBars: options.warmupBars }, model: serialized, featureSchema: model.featureNames.map((name, order) => ({ name, type: "number", order })), preprocessing: { missing: "reject", scaling: "none" }, strategyConfigurations: options.strategies, decisionThresholds: { profitable: Number(model.parameters.decisionThreshold ?? 0.55) }, riskPolicy: options.riskPolicy, trainingMetadata: options.trainingMetadata, modelCard: `# ${model.id}\n\nTime-series ensemble trained with chronological validation. Predictions are venue-independent and must pass an external risk policy before simulated execution.`, testVectors: options.sampleInputs.map((input, index) => ({ input, expected: predictions[index] })) };
}

export function importModelBundle(bundle: ModelBundle) {
  if (bundle.compatibilityVersion !== "1.0") throw new Error(`Unsupported bundle compatibility version: ${bundle.compatibilityVersion}`); if (stableHash(JSON.stringify(bundle.model)) !== bundle.manifest.checksum) throw new Error("Model bundle checksum mismatch"); const model = deserializeModel(bundle.model); if (bundle.featureSchema.length !== model.featureNames.length || bundle.featureSchema.some((feature, index) => feature.name !== model.featureNames[index] || feature.order !== index)) throw new Error("Model bundle feature schema mismatch"); for (const vector of bundle.testVectors) { if (vector.input.length !== model.featureNames.length) throw new Error("Model bundle test-vector width mismatch"); const actual = model.predict([vector.input], [vector.expected.timestamp])[0]; for (const key of ["expectedReturn", "probabilityProfitable", "targetExposure"] as const) if (Math.abs(actual[key] - vector.expected[key]) > 1e-10) throw new Error(`Model bundle parity failure: ${key}`); if (actual.direction !== vector.expected.direction) throw new Error("Model bundle parity failure: direction"); } return model;
}
