import type { Candle, ModelPrediction, Trade } from "./contracts";
import { clamp, stableHash } from "./math";

export type PaperStatus = "created" | "running" | "paused" | "stopped";
export interface PaperConfiguration { sessionId: string; modelId: string; modelVersion: string; provider?: string; marketType?: "spot"|"futures"|"commodity"; symbol: string; timeframe: string; initialCash: number; feeBps: number; spreadBps: number; slippageBps: number; maxExposure: number; maxDrawdown: number; }
export interface PaperState { status: PaperStatus; cash: number; quantity: number; averagePrice: number; equity: number; peakEquity: number; lastTimestamp: number | null; predictions: ModelPrediction[]; trades: Trade[]; processedEventIds: string[]; }

export function initialPaperState(configuration: PaperConfiguration): PaperState { if (configuration.initialCash <= 0) throw new Error("Paper cash must be positive"); return { status: "created", cash: configuration.initialCash, quantity: 0, averagePrice: 0, equity: configuration.initialCash, peakEquity: configuration.initialCash, lastTimestamp: null, predictions: [], trades: [], processedEventIds: [] }; }

export function transitionPaperState(state: PaperState, action: "start" | "pause" | "resume" | "emergency-stop") {
  if (action === "start" && state.status !== "created") throw new Error("Only a created paper session can start"); if (action === "pause" && state.status !== "running") throw new Error("Only a running paper session can pause"); if (action === "resume" && state.status !== "paused") throw new Error("Only a paused paper session can resume"); if (action === "emergency-stop" && state.status === "stopped") return state; return { ...state, status: action === "pause" ? "paused" as const : action === "emergency-stop" ? "stopped" as const : "running" as const };
}

export function processCompletedCandle(configuration: PaperConfiguration, state: PaperState, candle: Candle, prediction: ModelPrediction) {
  if (state.status !== "running") throw new Error("Paper session is not running"); if (!candle.complete) throw new Error("Incomplete candles are rejected by paper trading"); if (state.lastTimestamp !== null && candle.timestamp <= state.lastTimestamp) { const duplicate = state.lastTimestamp === candle.timestamp; if (duplicate) return state; throw new Error("Out-of-order paper candle rejected"); }
  const eventId = stableHash(`${configuration.sessionId}:${candle.symbol}:${candle.timeframe}:${candle.timestamp}`); if (state.processedEventIds.includes(eventId)) return state; let next = { ...state, predictions: [...state.predictions, prediction].slice(-1000), processedEventIds: [...state.processedEventIds, eventId].slice(-5000), lastTimestamp: candle.timestamp }; next.equity = next.cash + next.quantity * candle.close; next.peakEquity = Math.max(next.peakEquity, next.equity); const drawdown = next.peakEquity ? (next.peakEquity - next.equity) / next.peakEquity : 0; const exposure = drawdown >= configuration.maxDrawdown ? 0 : clamp(prediction.targetExposure, -configuration.maxExposure, configuration.maxExposure); const targetQuantity = next.equity * exposure / candle.close; const delta = targetQuantity - next.quantity;
  if (Math.abs(delta * candle.close) > 0.01) { const side = delta > 0 ? "buy" as const : "sell" as const; const costRate = configuration.spreadBps / 20_000 + configuration.slippageBps / 10_000; const fillPrice = candle.close * (1 + (side === "buy" ? costRate : -costRate)); const fee = Math.abs(delta * fillPrice) * configuration.feeBps / 10_000; const closing = next.quantity && Math.sign(delta) !== Math.sign(next.quantity) ? Math.min(Math.abs(delta), Math.abs(next.quantity)) : 0; const realizedPnl = closing * (fillPrice - next.averagePrice) * Math.sign(next.quantity); next.cash -= delta * fillPrice + fee; const newQuantity = next.quantity + delta; const averagePrice = newQuantity === 0 ? 0 : next.quantity === 0 || Math.sign(newQuantity) !== Math.sign(next.quantity) ? fillPrice : Math.sign(delta) === Math.sign(next.quantity) ? (Math.abs(next.quantity) * next.averagePrice + Math.abs(delta) * fillPrice) / Math.abs(newQuantity) : next.averagePrice; const trade: Trade = { id: `paper_${eventId}`, strategyId: configuration.modelId, symbol: candle.symbol, side, quantity: Math.abs(delta), requestedPrice: candle.close, fillPrice, timestamp: candle.timestamp, fee, slippage: Math.abs(delta) * Math.abs(fillPrice - candle.close), realizedPnl }; next = { ...next, quantity: newQuantity, averagePrice, trades: [...next.trades, trade].slice(-2000) }; }
  next.equity = next.cash + next.quantity * candle.close; return next;
}

export function maturePaperObservations(state: PaperState, horizonBars: number) {
  if (horizonBars < 1) throw new Error("Prediction horizon must be positive"); return state.predictions.slice(0, Math.max(0, state.predictions.length - horizonBars)).map((prediction, index) => ({ ...prediction, maturedByIndex: index + horizonBars }));
}
