import type { Candle, Parameters, StrategyPlugin, StrategySignal } from "./contracts";
import { requireIndicator } from "./indicators";
import { clamp, stableHash } from "./math";

type SignalRule = (candles: readonly Candle[], parameters: Parameters) => Array<{ direction: -1 | 0 | 1; confidence: number; stop?: number; target?: number; reason: string }>;

function strategy(id: string, name: string, description: string, indicators: string[], warmupBars: number, rule: SignalRule, parameters: StrategyPlugin["parameters"] = {}): StrategyPlugin {
  return {
    id, name, description, kind: "strategy", version: "1.0.0", interfaceVersion: "1.0", deterministic: true, parameters,
    dependencies: { requiredFields: ["timestamp", "open", "high", "low", "close", "volume", "complete"], marketTypes: ["spot", "futures", "commodity"], timeframes: "any", warmupBars, sources: ["candles"], indicators },
    generate(candles, supplied = {}) {
      const resolved = Object.fromEntries(Object.entries(parameters).map(([key, definition]) => [key, supplied[key] ?? definition.default]));
      const configurationVersion = stableHash(JSON.stringify({ id, version: "1.0.0", parameters: resolved }));
      return rule(candles, resolved).map((signal, index): StrategySignal => ({
        timestamp: candles[index].timestamp, direction: signal.direction, confidence: clamp(signal.confidence, 0, 1), desiredExposure: clamp(signal.direction * signal.confidence, -1, 1), stop: signal.stop, target: signal.target,
        metadata: { reason: signal.reason }, strategyId: id, strategyVersion: "1.0.0", configurationVersion,
      }));
    },
  };
}

const integer = (value: number, description: string, minimum = 2, maximum = 500) => ({ type: "integer" as const, default: value, minimum, maximum, description });
const number = (value: number, description: string, minimum = 0, maximum = 100) => ({ type: "number" as const, default: value, minimum, maximum, description });
const neutral = (reason: string) => ({ direction: 0 as const, confidence: 0, reason });

export const STRATEGY_PLUGINS: StrategyPlugin[] = [
  strategy("buy-and-hold", "Buy and Hold", "Long-only baseline entered after the first completed candle.", [], 1, (candles) => candles.map((_, index) => index === 0 ? neutral("Waiting for first completed bar") : ({ direction: 1, confidence: 1, reason: "Baseline long exposure" }))),
  strategy("moving-average-crossover", "Moving Average Crossover", "Fast EMA above or below slow EMA.", ["ema"], 50, (candles, p) => {
    const fastLength = Number(p.fast); const slowLength = Number(p.slow); const close = candles.map((c) => c.close); const fast = requireIndicator("ema").calculate(candles, { period: fastLength }).ema; const slow = requireIndicator("ema").calculate(candles, { period: slowLength }).ema;
    return candles.map((_, i) => fast[i] === null || slow[i] === null ? neutral("Warm-up") : ({ direction: fast[i]! > slow[i]! ? 1 as const : -1 as const, confidence: clamp(Math.abs(fast[i]! - slow[i]!) / close[i] * 30, 0.15, 1), reason: fast[i]! > slow[i]! ? "Fast EMA above slow EMA" : "Fast EMA below slow EMA" }));
  }, { fast: integer(20, "Fast EMA period"), slow: integer(50, "Slow EMA period") }),
  strategy("rsi-mean-reversion", "RSI Mean Reversion", "Fades momentum extremes and exits in the neutral region.", ["rsi"], 14, (candles, p) => { const values = requireIndicator("rsi").calculate(candles, { period: p.period }).rsi; const low = Number(p.oversold); const high = Number(p.overbought); return values.map((value) => value === null ? neutral("Warm-up") : value < low ? ({ direction: 1, confidence: clamp((low - value) / low + 0.35, 0, 1), reason: "RSI oversold" }) : value > high ? ({ direction: -1, confidence: clamp((value - high) / (100 - high) + 0.35, 0, 1), reason: "RSI overbought" }) : neutral("RSI neutral")); }, { period: integer(14, "RSI period"), oversold: number(30, "Oversold threshold", 1, 49), overbought: number(70, "Overbought threshold", 51, 99) }),
  strategy("macd-momentum", "MACD Momentum", "Follows the direction and strength of the MACD histogram.", ["macd"], 34, (candles) => { const histogram = requireIndicator("macd").calculate(candles).histogram; return histogram.map((value, i) => value === null ? neutral("Warm-up") : ({ direction: value >= 0 ? 1 : -1, confidence: clamp(Math.abs(value) / candles[i].close * 100, 0.1, 1), reason: value >= 0 ? "Positive MACD histogram" : "Negative MACD histogram" })); }),
  strategy("bollinger-mean-reversion", "Bollinger Mean Reversion", "Fades closes outside the volatility envelope.", ["bollinger"], 20, (candles, p) => { const bands = requireIndicator("bollinger").calculate(candles, p); return candles.map((c, i) => bands.upper[i] === null ? neutral("Warm-up") : c.close < bands.lower[i]! ? ({ direction: 1, confidence: clamp((bands.lower[i]! - c.close) / c.close * 20 + 0.3, 0, 1), reason: "Close below lower band" }) : c.close > bands.upper[i]! ? ({ direction: -1, confidence: clamp((c.close - bands.upper[i]!) / c.close * 20 + 0.3, 0, 1), reason: "Close above upper band" }) : neutral("Inside bands")); }, { period: integer(20, "Band period"), deviations: number(2, "Standard deviations", 0.1, 10) }),
  strategy("donchian-breakout", "Donchian Breakout", "Trades closes beyond the prior channel to avoid same-bar look-ahead.", ["donchian", "atr"], 21, (candles, p) => { const channel = requireIndicator("donchian").calculate(candles, { period: p.period }); const atr = requireIndicator("atr").calculate(candles, { period: 14 }).atr; return candles.map((c, i) => i === 0 || channel.upper[i - 1] === null || atr[i] === null ? neutral("Warm-up") : c.close > channel.upper[i - 1]! ? ({ direction: 1, confidence: clamp((c.close - channel.upper[i - 1]!) / atr[i]! + 0.4, 0, 1), stop: c.close - 2 * atr[i]!, reason: "Close above prior Donchian high" }) : c.close < channel.lower[i - 1]! ? ({ direction: -1, confidence: clamp((channel.lower[i - 1]! - c.close) / atr[i]! + 0.4, 0, 1), stop: c.close + 2 * atr[i]!, reason: "Close below prior Donchian low" }) : neutral("Inside prior channel")); }, { period: integer(20, "Channel period") }),
  strategy("adx-trend-following", "ADX Trend Following", "Trades directional movement only when ADX confirms trend strength.", ["adx"], 28, (candles, p) => { const values = requireIndicator("adx").calculate(candles, { period: p.period }); const threshold = Number(p.threshold); return candles.map((_, i) => values.adx[i] === null || values.adx[i]! < threshold ? neutral("Trend strength below threshold") : ({ direction: values.plusDi[i]! >= values.minusDi[i]! ? 1 : -1, confidence: clamp((values.adx[i]! - threshold) / (100 - threshold) + 0.35, 0, 1), reason: values.plusDi[i]! >= values.minusDi[i]! ? "+DI leads in strong trend" : "-DI leads in strong trend" })); }, { period: integer(14, "ADX period"), threshold: number(25, "Trend threshold", 1, 99) }),
  strategy("supertrend", "Supertrend", "Follows ATR-based Supertrend direction with a volatility stop.", ["supertrend"], 10, (candles, p) => { const values = requireIndicator("supertrend").calculate(candles, p); return candles.map((c, i) => values.direction[i] === null ? neutral("Warm-up") : ({ direction: values.direction[i]! >= 0 ? 1 : -1, confidence: 0.7, stop: values.supertrend[i]!, reason: values.direction[i]! >= 0 ? "Price above Supertrend" : "Price below Supertrend" })); }, { period: integer(10, "ATR period"), multiplier: number(3, "ATR multiplier", 0.1, 20) }),
  strategy("momentum-roc", "Momentum / ROC", "Trades the sign and magnitude of rate of change.", ["roc"], 12, (candles, p) => { const values = requireIndicator("roc").calculate(candles, { period: p.period }).roc; const threshold = Number(p.threshold); return values.map((value) => value === null || Math.abs(value) < threshold ? neutral("Momentum below threshold") : ({ direction: value > 0 ? 1 : -1, confidence: clamp(Math.abs(value) / 10, 0.15, 1), reason: value > 0 ? "Positive rate of change" : "Negative rate of change" })); }, { period: integer(12, "ROC period"), threshold: number(0.5, "Minimum absolute ROC", 0, 50) }),
  strategy("multi-indicator-consensus", "Multi-Indicator Consensus", "Combines trend, momentum, and mean-reversion votes.", ["ema", "rsi", "macd"], 34, (candles) => { const fast = requireIndicator("ema").calculate(candles, { period: 12 }).ema; const slow = requireIndicator("ema").calculate(candles, { period: 26 }).ema; const strength = requireIndicator("rsi").calculate(candles, { period: 14 }).rsi; const momentum = requireIndicator("macd").calculate(candles).histogram; return candles.map((_, i) => { if (slow[i] === null || strength[i] === null || momentum[i] === null) return neutral("Warm-up"); const votes = [fast[i]! > slow[i]! ? 1 : -1, strength[i]! > 55 ? 1 : strength[i]! < 45 ? -1 : 0, momentum[i]! > 0 ? 1 : -1]; const score = votes.reduce((sum, vote) => sum + vote, 0); return Math.abs(score) < 2 ? neutral("No indicator consensus") : ({ direction: score > 0 ? 1 : -1, confidence: Math.abs(score) / 3, reason: `${Math.abs(score)}-vote directional consensus` }); }); }),
  strategy("volatility-filtered-trend", "Volatility-Filtered Trend", "EMA trend strategy enabled only in a configured ATR regime.", ["ema", "atr"], 50, (candles, p) => { const fast = requireIndicator("ema").calculate(candles, { period: 20 }).ema; const slow = requireIndicator("ema").calculate(candles, { period: 50 }).ema; const atr = requireIndicator("atr").calculate(candles, { period: 14 }).atr; const min = Number(p.minimumAtrPercent); const max = Number(p.maximumAtrPercent); return candles.map((c, i) => { if (slow[i] === null || atr[i] === null) return neutral("Warm-up"); const volatility = atr[i]! / c.close * 100; if (volatility < min || volatility > max) return neutral("Outside volatility regime"); return { direction: fast[i]! >= slow[i]! ? 1 : -1, confidence: clamp(Math.abs(fast[i]! - slow[i]!) / atr[i]!, 0.2, 1), stop: fast[i]! >= slow[i]! ? c.close - 2 * atr[i]! : c.close + 2 * atr[i]!, reason: "Trend confirmed inside volatility regime" }; }); }, { minimumAtrPercent: number(0.2, "Minimum ATR percent", 0, 100), maximumAtrPercent: number(8, "Maximum ATR percent", 0.1, 100) }),
];

export const strategyRegistry = new Map(STRATEGY_PLUGINS.map((plugin) => [plugin.id, plugin]));

export function requireStrategy(id: string) {
  const plugin = strategyRegistry.get(id);
  if (!plugin) throw new Error(`Unknown strategy plugin: ${id}`);
  return plugin;
}
